language: node_js
os: osx
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
install:
  - npm i -g eslint snyk codecov codeclimate-test-reporter
  - npm i
script:
  - snyk auth $SNYK_TOKEN
  - snyk test
  - npm run test:coverage
  - npm run lint
  - npm run build
after_success:
  - snyk monitor
  - codecov
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
