language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run snyk
  - npm test
  - npm run test:coverage
  - npm run lint
  - npm run build
deploy:
  provider: netlify
  site: workflowbuilder.netlify.com
  auth: $deploy_token
  edge: true # opt in to dpl v2
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
