language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
install:
  - npm i -g snyk codecov codeclimate-test-reporter
  - npm i
script:
  - snyk test
  - npm run test:coverage
  - npm run lint
  - npm run build
after_success:
  - snyk monitor
  - codecov
  - codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  provider: netlify
  site: workflowbuilder.netlify.com
  auth: $NETLIFY_TOKEN
  edge: true
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
